-- คัดลอกโค้ดนี้ไปวางใน SQL Editor ของ Supabase และกด RUN
-- Script นี้จะเคลียร์ตารางเก่าและสร้างใหม่ใน Schema "public" 

-- 1. เคลียร์ตารางเดิม (Table-kik) ใน public เพื่อป้องกันปัญหา
DROP TABLE IF EXISTS public."Table-kik";
-- (Optional) ลบตาราง users เก่าถ้าไม่ใช้แล้ว แต่เก็บไว้ก่อนก็ได้
-- DROP TABLE IF EXISTS public.users;

-- 2. สร้างตาราง Table-kik (ตารางเวร)
CREATE TABLE IF NOT EXISTS public."Table-kik" (
  id text primary key,
  staff_id text not null,
  date text not null,
  shift_type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. สร้างตาราง monthly_roster_status (สถานะการประกาศ)
CREATE TABLE IF NOT EXISTS public.monthly_roster_status (
    month_key text primary key, 
    is_published boolean default false,
    published_by text,
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. สร้างตาราง users-table-kik (ตารางผู้ใช้งาน) ** เปลี่ยนชื่อตามที่ขอ **
CREATE TABLE IF NOT EXISTS public."users-table-kik" (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  name text not null,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. ให้สิทธิ์การใช้งาน
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 6. เพิ่มข้อมูลผู้ใช้งานเริ่มต้นลงใน users-table-kik
INSERT INTO public."users-table-kik" (username, password, name, role) VALUES
('tor', 'tor', 'พี่ต่อ', 'user'),
('kik', 'kik', 'พี่กิ๊ก', 'user'),
('jhim', 'jhim', 'พี่จิ๋ม', 'user'),
('pan', 'pan', 'น้องปาน', 'user'),
('top', 'top', 'พี่ท๊อป', 'user'),
('team', 'team', 'พี่ทีม', 'user'),
('admin', '1234', 'Admin', 'admin')
ON CONFLICT (username) DO NOTHING;

-- 7. เปิดการใช้งาน Row Level Security (RLS)
ALTER TABLE public."users-table-kik" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Table-kik" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_roster_status ENABLE ROW LEVEL SECURITY;

-- 8. ล้าง Policies เก่าทิ้งทั้งหมดป้องกัน Error
DROP POLICY IF EXISTS "Allow all access" ON public.monthly_roster_status;
DROP POLICY IF EXISTS "Allow all access" ON public."Table-kik";

-- ล้าง Policies ของ users-table-kik
DROP POLICY IF EXISTS "Allow all access" ON public."users-table-kik";

-- 9. สร้าง Policies ใหม่ (อนุญาตให้ทุกคนอ่าน/เขียนได้เพื่อความสะดวก)
CREATE POLICY "Allow all access" ON public."users-table-kik" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON public.monthly_roster_status FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON public."Table-kik" FOR ALL USING (true) WITH CHECK (true);
