-- คัดลอกโค้ดนี้ไปวางใน SQL Editor ของ Supabase และกด RUN
-- Script นี้ถูกปรับปรุงให้ Run ซ้ำได้โดยไม่ Error

-- 1. สร้าง Schema "Work-Shift-Schedule"
CREATE SCHEMA IF NOT EXISTS "Work-Shift-Schedule";
GRANT USAGE ON SCHEMA "Work-Shift-Schedule" TO anon, authenticated, service_role;

-- 2. สร้างตาราง Users
CREATE TABLE IF NOT EXISTS "Work-Shift-Schedule".users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  name text not null,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. สร้างตาราง Table-kik (ลบของเดิมถ้ามีเพื่อให้มั่นใจว่า Schema ตรงกัน)
DROP TABLE IF EXISTS "Work-Shift-Schedule"."Table-kik";

CREATE TABLE "Work-Shift-Schedule"."Table-kik" (
  id text primary key,
  staff_id text not null,
  date text not null,
  shift_type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. ให้สิทธิ์
GRANT ALL ON ALL TABLES IN SCHEMA "Work-Shift-Schedule" TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA "Work-Shift-Schedule" TO anon, authenticated, service_role;

-- 5. เพิ่มข้อมูลเริ่มต้น
INSERT INTO "Work-Shift-Schedule".users (username, password, name, role) VALUES
('tor', 'tor', 'พี่ต่อ', 'user'),
('kik', 'kik', 'พี่กิ๊ก', 'user'),
('jhim', 'jhim', 'พี่จิ๋ม', 'user'),
('pan', 'pan', 'น้องปาน', 'user'),
('top', 'top', 'พี่ท๊อป', 'user'),
('team', 'team', 'พี่ทีม', 'user'),
('admin', '1234', 'Admin', 'admin')
ON CONFLICT (username) DO NOTHING;

-- 6. เปิด RLS
ALTER TABLE "Work-Shift-Schedule".users ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Work-Shift-Schedule"."Table-kik" ENABLE ROW LEVEL SECURITY;

-- 7. ลบ Policies เก่าออกก่อน (เพื่อป้องกัน Error 'already exists')
DROP POLICY IF EXISTS "Allow read access for all" ON "Work-Shift-Schedule".users;
DROP POLICY IF EXISTS "Allow insert access for all" ON "Work-Shift-Schedule".users;
DROP POLICY IF EXISTS "Allow update access for all" ON "Work-Shift-Schedule".users;
DROP POLICY IF EXISTS "Allow delete access for all" ON "Work-Shift-Schedule".users;

DROP POLICY IF EXISTS "Allow read access for all" ON "Work-Shift-Schedule"."Table-kik";
DROP POLICY IF EXISTS "Allow insert access for all" ON "Work-Shift-Schedule"."Table-kik";
DROP POLICY IF EXISTS "Allow update access for all" ON "Work-Shift-Schedule"."Table-kik";
DROP POLICY IF EXISTS "Allow delete access for all" ON "Work-Shift-Schedule"."Table-kik";

-- 8. สร้าง Policies ใหม่
-- Users
CREATE POLICY "Allow read access for all" ON "Work-Shift-Schedule".users FOR SELECT USING (true);
CREATE POLICY "Allow insert access for all" ON "Work-Shift-Schedule".users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update access for all" ON "Work-Shift-Schedule".users FOR UPDATE USING (true);
CREATE POLICY "Allow delete access for all" ON "Work-Shift-Schedule".users FOR DELETE USING (true);

-- Table-kik
CREATE POLICY "Allow read access for all" ON "Work-Shift-Schedule"."Table-kik" FOR SELECT USING (true);
CREATE POLICY "Allow insert access for all" ON "Work-Shift-Schedule"."Table-kik" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update access for all" ON "Work-Shift-Schedule"."Table-kik" FOR UPDATE USING (true);
CREATE POLICY "Allow delete access for all" ON "Work-Shift-Schedule"."Table-kik" FOR DELETE USING (true);
