-- คัดลอกโค้ดนี้ไปวางใน SQL Editor ของ Supabase และกด RUN

-- 1. สร้าง Schema ใหม่ชื่อ "Work-Shift-Schedule"
CREATE SCHEMA IF NOT EXISTS "Work-Shift-Schedule";

-- 2. ให้สิทธิ์การเข้าถึง Schema แก่ API
GRANT USAGE ON SCHEMA "Work-Shift-Schedule" TO anon, authenticated, service_role;

-- 3. สร้างตาราง Users ใน Schema ใหม่
CREATE TABLE "Work-Shift-Schedule".users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  name text not null,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. สร้างตาราง Assignments ใน Schema ใหม่
CREATE TABLE "Work-Shift-Schedule".assignments (
  id text primary key,
  staff_id text not null,
  date text not null,
  shift_type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. ให้สิทธิ์ตารางทั้งหมดใน Schema
GRANT ALL ON ALL TABLES IN SCHEMA "Work-Shift-Schedule" TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA "Work-Shift-Schedule" TO anon, authenticated, service_role;

-- 6. เพิ่มข้อมูลผู้ใช้งานเริ่มต้น
INSERT INTO "Work-Shift-Schedule".users (username, password, name, role) VALUES
('tor', 'tor', 'พี่ต่อ', 'user'),
('kik', 'kik', 'พี่กิ๊ก', 'user'),
('jhim', 'jhim', 'พี่จิ๋ม', 'user'),
('pan', 'pan', 'น้องปาน', 'user'),
('top', 'top', 'พี่ท๊อป', 'user'),
('team', 'team', 'พี่ทีม', 'user'),
('admin', '1234', 'Admin', 'admin')
ON CONFLICT (username) DO NOTHING;

-- 7. เปิดใช้งาน Row Level Security (RLS)
ALTER TABLE "Work-Shift-Schedule".users ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Work-Shift-Schedule".assignments ENABLE ROW LEVEL SECURITY;

-- 8. สร้าง Policies เพื่ออนุญาตให้เข้าถึงข้อมูล
-- สำหรับ Users
CREATE POLICY "Allow read access for all" ON "Work-Shift-Schedule".users FOR SELECT USING (true);
CREATE POLICY "Allow insert access for all" ON "Work-Shift-Schedule".users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update access for all" ON "Work-Shift-Schedule".users FOR UPDATE USING (true);
CREATE POLICY "Allow delete access for all" ON "Work-Shift-Schedule".users FOR DELETE USING (true);

-- สำหรับ Assignments
CREATE POLICY "Allow read access for all" ON "Work-Shift-Schedule".assignments FOR SELECT USING (true);
CREATE POLICY "Allow insert access for all" ON "Work-Shift-Schedule".assignments FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update access for all" ON "Work-Shift-Schedule".assignments FOR UPDATE USING (true);
CREATE POLICY "Allow delete access for all" ON "Work-Shift-Schedule".assignments FOR DELETE USING (true);

-- *** คำเตือน ***
-- หลังจาก Run SQL นี้เสร็จแล้ว อย่าลืมไปที่ Supabase Dashboard -> Settings -> API
-- ในหัวข้อ "Exposed Schemas" ให้กด Add schema "Work-Shift-Schedule" เข้าไปด้วย
-- ไม่อย่างนั้น App จะหาตารางไม่เจอ